#!/usr/bin/env bash
# Bootstrap Agent OS into a repository root (run from repo root, not from inside .ai/ only).
set -euo pipefail

AI_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
TPL="${AI_ROOT}/templates/work"

# Repo root: git root containing .ai/, or AI_ROOT itself when this repository *is* the Agent OS tree.
# Honor an explicit REPO_ROOT env override so scaffold can write into a TARGET
# directory when bootstrap.sh is invoked from an external source .ai
# (in-place bootstrap via @deploy-files). e.g.
#   REPO_ROOT=/mnt/work/Projects/tools-project bash /mnt/work/Projects/.ai/templates/bootstrap.sh
if [[ -n "${REPO_ROOT:-}" ]]; then
  REPO_ROOT="$(cd "$REPO_ROOT" && pwd)"
elif [[ -d "${AI_ROOT}/.git" ]]; then
  REPO_ROOT="${AI_ROOT}"
elif [[ -d "${AI_ROOT}/../.git" ]] && [[ -d "${AI_ROOT}/templates" ]]; then
  REPO_ROOT="$(cd "${AI_ROOT}/.." && pwd)"
else
  REPO_ROOT="${AI_ROOT}"
fi

WORK="${REPO_ROOT}/.work"

copy_if_missing() {
  local src="$1" dest="$2"
  if [[ -e "${dest}" ]]; then
    echo "skip (exists): ${dest}"
  else
    mkdir -p "$(dirname "${dest}")"
    cp "${src}" "${dest}"
    echo "created: ${dest}"
  fi
}

echo "Agent OS bootstrap"
echo "  AI_ROOT=${AI_ROOT}"
echo "  REPO_ROOT=${REPO_ROOT}"
echo ""

mkdir -p "${WORK}"

copy_if_missing "${TPL}/README.md.template" "${WORK}/README.md"
copy_if_missing "${TPL}/context/HANDOFF.md.template" "${WORK}/context/HANDOFF.md"
copy_if_missing "${TPL}/plans/NEXT.md.template" "${WORK}/plans/NEXT.md"
copy_if_missing "${TPL}/plans/ASSUMPTIONS.md.template" "${WORK}/plans/ASSUMPTIONS.md"
copy_if_missing "${TPL}/plans/RISK_REGISTRY.md.template" "${WORK}/plans/RISK_REGISTRY.md"
copy_if_missing "${TPL}/plans/UNKNOWNS.md.template" "${WORK}/plans/UNKNOWNS.md"
copy_if_missing "${TPL}/touch-scope.template" "${WORK}/touch-scope"
copy_if_missing "${TPL}/PROTECTED_SURFACES.template" "${WORK}/PROTECTED_SURFACES.json"
copy_if_missing "${TPL}/decisions/README.md.template" "${WORK}/decisions/README.md"
copy_if_missing "${TPL}/prompts/README.md.template" "${WORK}/prompts/README.md"
copy_if_missing "${TPL}/features/README.md.template" "${WORK}/features/README.md"
copy_if_missing "${TPL}/docs/README.md.template" "${WORK}/docs/README.md"
copy_if_missing "${TPL}/docs/features/README.md.template" "${WORK}/docs/features/README.md"

for dir in foundation full operations proposals archives; do
  mkdir -p "${WORK}/plans/${dir}"
  touch "${WORK}/plans/${dir}/.gitkeep"
done

# Create output-sink dirs (not populated by bootstrap; appear when work runs)
for dir in analysis scripts; do
  mkdir -p "${WORK}/${dir}"
  touch "${WORK}/${dir}/.gitkeep"
done

# Create docs subdirectories (populated by @docs skill + vendor integration cache)
for dir in guides tutorials reference integration; do
  mkdir -p "${WORK}/docs/${dir}"
  touch "${WORK}/docs/${dir}/.gitkeep"
done

# Project-owned binding standards (generated by @plan-foundation greenfield P3).
# Always under .work/ — never at repo root, never under .ai/, never from $AGENT_OS_SOURCE.
mkdir -p "${WORK}/standards"
touch "${WORK}/standards/.gitkeep"
echo "scaffold: ${WORK}/standards/ (project binding standards — under .work/ only)"

# Remove deprecated repo-root scaffold dirs (pre-v0.5.2 layout). Migrate only when
# empty or .gitkeep-only — never delete populated project content.
purge_legacy_repo_root_scaffold() {
  local d="$1"
  # Never touch project memory under .work/
  case "$d" in
    "${REPO_ROOT}/.work"|"${REPO_ROOT}/.work"/*) return 0 ;;
  esac
  if [[ ! -e "$d" ]]; then
    return 0
  fi
  if [[ -L "$d" ]]; then
    rm -f "$d"
    echo "removed (deprecated symlink): ${d}"
    return 0
  fi
  if [[ -d "$d" ]] && [[ -z "$(find "$d" -mindepth 1 ! -name '.gitkeep' -print -quit 2>/dev/null)" ]]; then
    rm -rf "$d"
    echo "removed (deprecated repo-root scaffold): ${d}"
  fi
}
purge_legacy_repo_root_scaffold "${REPO_ROOT}/standards"
purge_legacy_repo_root_scaffold "${REPO_ROOT}/docs/integration"
# Remove docs/ only when it is the legacy integration-only stub (no other subdirs/files).
if [[ -d "${REPO_ROOT}/docs" ]] && [[ ! -d "${REPO_ROOT}/docs/integration" ]]; then
  :
elif [[ -d "${REPO_ROOT}/docs" ]]; then
  other_docs="$(find "${REPO_ROOT}/docs" -mindepth 1 -maxdepth 1 ! -name integration -print -quit 2>/dev/null || true)"
  if [[ -z "$other_docs" ]]; then
    int_only=1
    if [[ -d "${REPO_ROOT}/docs/integration" ]]; then
      if [[ -n "$(find "${REPO_ROOT}/docs/integration" -mindepth 1 ! -name '.gitkeep' -print -quit 2>/dev/null)" ]]; then
        int_only=0
      fi
    fi
    if [[ "$int_only" -eq 1 ]]; then
      rm -rf "${REPO_ROOT}/docs"
      echo "removed (deprecated repo-root scaffold): ${REPO_ROOT}/docs"
    fi
  fi
fi

if [[ -n "${BOOTSTRAP_SKIP_CURSERRULES:-}" ]]; then
  echo "skip (.cursorrules owned by caller): ${REPO_ROOT}/.cursorrules"
elif [[ ! -f "${REPO_ROOT}/.cursorrules" ]]; then
  if [[ -f "${AI_ROOT}/templates/cursorrules.template" ]]; then
    cp "${AI_ROOT}/templates/cursorrules.template" "${REPO_ROOT}/.cursorrules"
    echo "created: ${REPO_ROOT}/.cursorrules (from template — edit all REPLACE: tokens)"
  fi
else
  echo "skip (exists): ${REPO_ROOT}/.cursorrules"
fi

if [[ -f "${AI_ROOT}/templates/DOCS_TECH_STACK.md.template" ]]; then
  dest="${REPO_ROOT}/DOCS_TECH_STACK.md"
  if [[ ! -f "${dest}" ]]; then
    cp "${AI_ROOT}/templates/DOCS_TECH_STACK.md.template" "${dest}"
    echo "created: ${dest}"
  else
    echo "skip (exists): ${dest}"
  fi
fi

echo ""
echo "Next steps:"
echo "  1. Edit ${REPO_ROOT}/.cursorrules — replace every REPLACE: token"
echo "  2. Run @plan-foundation greenfield (generates this project's own ${WORK}/standards/*.md — CONVENTIONS, FEATURE_STANDARD, DIRECTORY_MAP, etc. — plus foundation docs 01–04)"
echo "  3. Run @session-control start"
echo "  4. Using opencode? opencode.json is created from template when missing (see scripts/install-opencode-config.sh)"
echo ""

bash "${AI_ROOT}/scripts/install-git-hooks.sh" 2>/dev/null || true

REPO_ROOT="${REPO_ROOT}" AI_SOURCE="${AI_ROOT}" bash "${AI_ROOT}/scripts/install-opencode-config.sh" 2>/dev/null || true

echo "Templates for foundation/full/SPEC/ADR: ${AI_ROOT}/templates/work/"
